name: app_info_extractor
description: A Flutter plugin to extract metadata, version, and signatures from installed applications.
version: 1.0.0
homepage: https://meetvishavadia.dev
repository: https://github.com/Technophyle-0926/app_info_extractor
issue_tracker: https://github.com/Technophyle-0926/app_info_extractor/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  archive: ^4.0.9
  collection: ^1.19.1
  fixnum: ^1.1.1
  flutter:
    sdk: flutter
  plist_parser: ^0.2.7
  protobuf: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
